name: Sync Parent Branch

on:
  push:
    branches:
      - parent

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config --global user.email "safderareepattamannil@gmail.com"
          git config --global user.name "Safder Areepattamannil"

      - name: Fetch latest changes
        run: git fetch origin

      - name: Merge changes into parent branch
        run: |
          git checkout child
          git merge --allow-unrelated-histories origin/parent 
          git push origin child
