name: Sync Branch if postfix in name
on:
  push:
    branches:
      - '*'

jobs:
  check_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Parent Branch
      - name: Get current branch name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # Determine postfix branch name
      - name: Determine postfix branch
        id: parent_branch
        run: echo "CHILD_BRANCH=${GITHUB_REF#refs/heads/}-postfix" >> $GITHUB_ENV

      - name: Configure Git user
        run: |
          git config --global user.email "safderareepattamannil@gmail.com"
          git config --global user.name "Safder Areepattamannil"

      - name: Fetch latest changes
        run: git fetch origin

      - name: Merge changes into parent branch
        if: ${{ contains(env.BRANCH_NAME, '-postfix') }}
        run: |
          git checkout ${{ env.CHILD_BRANCH }}
          git merge --allow-unrelated-histories --strategy-option=theirs origin/${{ env.BRANCH_NAME }}
          git push origin ${{ env.CHILD_BRANCH }}