name: Sync Branch if postfix in name
on:
  push:
    branches:
      - '*'
# Figure out a way to make this only run when there exists a branch with "parent-postfix" in the name
jobs:
  check_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine postfix branch
        id: parent_branch
        run: echo "CHILD_BRANCH=${GITHUB_REF#refs/heads/}-postfix" >> $GITHUB_ENV

      - name: Configure Git user
        run: |
          git config --global user.email "safderareepattamannil@gmail.com"
          git config --global user.name "Safder Areepattamannil"

      - name: Fetch latest changes
        run: git fetch origin

      - name: Merge changes into child branch
        run: |
          git checkout ${{ env.CHILD_BRANCH }}
          git merge --allow-unrelated-histories --strategy-option=theirs origin/${{ env.BRANCH_NAME }}
          git push origin ${{ env.CHILD_BRANCH }}